### ISSUE TITLE
For Each NOAA Station, Extract Weather Data

### ISSUE THREAD

**Issue by saifrahmed** [DataKind-DC/audubon-cbc#12]
As discussed with @renzo: 

For Each NOAA Station, Extract the following weather data
- Precipitation
- If Snowing
- Temperature High
- Temperature Low
- Wind Speed

We want to get this data for *count_data* from the file 
audubon-cbc/bird_count_cleaned_may_29_2019.csv 

We need to get the station id from output.csv

We need to join output.csv and bird_count_cleaned_may_29_2019.csv files. The assumption is that the rows join 1:1. The station id is from the column closest_station (sample value: "CAMBRIDGE, MA US")
Station IDs can be obtained from https://www.ncdc.noaa.gov/cdo-web/api/v2/datasets?stationid=GHCND:USC00173046

We need to get the above weather data for the data of interest + station id.

**Comment by rectheworld** [comment]
Closing this ticket because is is covered in greater detail and more up to date data sources by an later issue.
