### ISSUE TITLE
Parse GHCN Data

### ISSUE THREAD

**Issue by minh5** [DataKind-DC/audubon-cbc#20]
GHCN has weather data that we can connect back to the Audubon Circles, however the data size is around 30gb uncompressed and 2gb compressed.

This is important because NOAA stations do not exist throughout the process and not all NOAA station are near Audubon Circles. The files are fixed width and in a weird format and is located here:
https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/

**Comment by rectheworld** [comment]
After some research we have found that Google has already put this data into a SQL interruptible format.

So to obtain the daily measures of weather data, we will be using the GHCN Daily database powered by Google [here] (https://console.cloud.google.com/marketplace/details/noaa-public/ghcn-d?filter=solution-type:dataset&id=9d500d1d-fda4-4413-a789-d8786fd6592e&pli=1)"
