### ISSUE TITLE
Find List of Acceptable NOAA Stations

### ISSUE THREAD

**Issue by minh5** [DataKind-DC/audubon-cbc#21]
Since NOAA stations pop up at different times and not all of them are located near an Audubon Circle, we need a list of NOAA stations that within at least 10km.

**Comment by rectheworld** [comment]
To obtain the daily measures of weather data, we will be using the GHCN Daily database powered by Google [here] (https://console.cloud.google.com/marketplace/details/noaa-public/ghcn-d?filter=solution-type:dataset&id=9d500d1d-fda4-4413-a789-d8786fd6592e&pli=1)"

In this dataset is the table ghcn_inventory. This file contains the data of the location of each station and the years they operated. Ticket #26 foes into more detail. 
#26
