### ISSUE TITLE
Determining reliability of temperature

### ISSUE THREAD

**Issue by jd1497** [DataKind-DC/audubon-cbc#23]
Ideas we should use:

- https://rmets.onlinelibrary.wiley.com/doi/pdf/10.1002/(SICI)1097-0088(199604)16:4%3C361::AID-JOC53%3E3.0.CO;2-F
-Kmeans
-KNN

**Comment by ijd5004** [comment]
(Ian D.) - Has anyone taken the lead on this yet?

**Comment by rectheworld** [comment]
@ijd5004 No, If you want it just assign yourself and create a branch.
(Also if you do, can you give a little more detail in the ticket on what this is?)

**Comment by rectheworld** [comment]
# Retiring
