### ISSUE TITLE
Resolve Discrepancies between GHCND Sources

### ISSUE THREAD

**Issue by minh5** [DataKind-DC/audubon-cbc#29]
There is GHCND data in BigQuery as a public [dataset](https://console.cloud.google.com/marketplace/details/noaa-public/ghcn-d?filter=solution-type:dataset&id=9d500d1d-fda4-4413-a789-d8786fd6592e&pli=1) as well as public [dataset](https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/) provided by the organization, which is parsed by using this python [script](https://github.com/davidhstocker/ghcndextractor).

Before proceeding with any analysis, we do need to figure out a source of truth. We have found discrepancies between the data in BQ and the .dly files provided. In particular if you run 

```
SELECT * FROM `bigquery-public-data.ghcn_d.ghcnd_1988` 
WHERE id = 'USS0010D24S' AND date = '1988-01-30'`
```

will return data for a station but does not exist when parsed using `ghcndextractor`. We will need to investigate and figure out why these values do not line up.

**Comment by Frankie-Figz** [comment]
If you go to https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/by_year/ (NOAA website) and look at the weather data corresponding to the year 1988 and you search for
 USS0010D24S,19880130
You get :
![Screenshot_20200207-141000_Slack](https://user-images.githubusercontent.com/39884538/74058243-9c641600-49b3-11ea-8c6f-406cb2e40710.jpg)

**Comment by Frankie-Figz** [comment]
The above comment would lead one to believe that the discrepancy is with the python script

**Comment by rectheworld** [comment]
From Jason @hemmendinger the library itself was not configured to pull in the values.  We have no reason to suspect data integrity issues.
